server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost1:8762/eureka/,http://localhost2:8763/eureka/

# Create other local hosts in c:\Windows\System32\Drivers\etc\hosts
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: localhost

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: localhost1

---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: localhost2