package com.application.email.service;

import java.util.ArrayList;
import java.util.List;

import javax.mail.MessagingException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import com.application.email.dto.EmailDetails;

@Component
public class SchedulingService {
	
	@Autowired
	private EmailService emailService;
	
	@Scheduled(fixedDelay=60000)
	public void triggerEmail() {
		List<String> toAddress = new ArrayList<>();
		toAddress.add("ravisharma.1062@gmail.com");
		
		EmailDetails emailDetails = new EmailDetails();
		emailDetails.setToAddress(toAddress);
		emailDetails.setSubject("Autogenerated Email from scheduler");
		emailDetails.setBody("Hi All, Its a test email. Don't worry, you are safe!!!");
		
		try {
			emailService.sendEmail(emailDetails);
		} catch (MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
